export const dynamic = 'force-dynamic'; 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from '@/components/Sidebar';
import { createClient } from '@/lib/supabase/server';
import { Toaster } from "@/components/ui/sonner"
import { SidebarProvider } from "@/context/SidebarContext";
import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lume",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen bg-slate-50">
            <Sidebar userEmail={user?.email} />
            
            <div className="flex-1 flex flex-col">
              {/* O Header agora é global! */}
              <Header user={user} />
              
              <main className="flex-1">
                {children}
              </main>
            </div>
            </div>
        </SidebarProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
